(defpackage :cl-bbs/handlers
  (:use :cl :cl-bbs/storage :cl-bbs/views)
  (:export #:handle-request))

(in-package :cl-bbs/handlers)

(defun parse-cookies (cookie-string)
  "Parses a Cookie header string like 'theme=dark; foo=bar' into an alist."
  (when cookie-string
    (let ((cookies '()))
      (dolist (pair (cl-ppcre:split ";\\s*" cookie-string))
        (let ((parts (cl-ppcre:split "=" pair)))
          (when (= (length parts) 2)
            (push (cons (cl-ppcre:regex-replace-all "^\\s+|\\s+$" (first parts) "")
                        (cl-ppcre:regex-replace-all "^\\s+|\\s+$" (second parts) ""))
                  cookies))))
      cookies)))

(defun get-theme-from-env (env)
  (let* ((headers (getf env :headers))
         (cookie-str (and headers (gethash "cookie" headers)))
         (cookies (parse-cookies cookie-str)))
    (or (cdr (assoc "theme" cookies :test #'string=)) "default")))

(defun get-board-description (board-name)
  (cond
    ((string= board-name "prog") "Programming")
    ((string= board-name "foo") "Foo Reference")
    (t (string-capitalize board-name))))

(defun generate-boards-html-list ()
  (let* ((sexp-dir (merge-pathnames "sexp/" cl-bbs/storage::*base-dir*))
         (paths (and (probe-file sexp-dir) (uiop:subdirectories sexp-dir)))
         (boards (sort (mapcar (lambda (path)
                                 (car (last (pathname-directory path))))
                               paths)
                       #'string<))
         (html-list ""))
    (dolist (board boards)
      (let ((desc (get-board-description board)))
        (setf html-list
              (format nil "~a<li><a href=\"/~a/\">/~a/</a> - <b>~a</b></li>~%"
                      html-list board board desc))))
    html-list))

(defun authenticate-admin (env)
  "Checks if the request has valid admin credentials in environment variables."
  (let* ((admin-user (or (uiop:getenv "SBBS_ADMIN_USER") "admin"))
         (admin-password (or (uiop:getenv "SBBS_ADMIN_PASSWORD") "superchanner"))
         (headers (getf env :headers))
         (auth-str (and headers (gethash "authorization" headers)))
         (creds (and auth-str (cl-ppcre:regex-replace-all "^Basic " auth-str ""))))
    (when creds
      (let* ((decoded (ignore-errors (cl-base64:base64-string-to-string creds)))
             (parts (and decoded (cl-ppcre:split ":" decoded :limit 2))))
        (and (= (length parts) 2)
             (string= (first parts) admin-user)
             (string= (second parts) admin-password))))))

(defun delete-board-dir (board)
  (let ((board-dir (merge-pathnames (format nil "sexp/~a/" board) *base-dir*)))
    (when (probe-file board-dir)
      (uiop:delete-directory-tree board-dir :validate t))))

(defun get-board-threads (dir)
  (let ((threads nil))
    (loop for i from 1 to 1000
          for filepath = (merge-pathnames (format nil "~D" i) dir)
          for exists = (probe-file filepath)
          do (when exists
               (let ((data (read-sexp-file filepath)))
                 (when data
                   (push (cons i data) threads)))))
    threads))

(defun get-flat-posts (posts-assoc)
  (when posts-assoc
    (let* ((cdr-val (cdr posts-assoc))
           (cadr-val (and (listp cdr-val) (car cdr-val))))
      (if (and (listp cadr-val) (listp (car cadr-val)))
          cadr-val
          cdr-val))))

(defun regenerate-board-index (board)
  (let* ((board-dir (merge-pathnames (format nil "sexp/~a/" board) *base-dir*))
         (threads-data (get-board-threads board-dir)))
    (if threads-data
        (let* ((sorted-threads 
                (sort threads-data
                      (lambda (a b)
                        (let* ((raw-a (if (and (consp (cdr a)) (consp (cadr a)) (consp (caadr a))) (cadr a) (cdr a)))
                               (raw-b (if (and (consp (cdr b)) (consp (cadr b)) (consp (caadr b))) (cadr b) (cdr b)))
                               (posts-assoc-a (assoc 'cl-bbs/models::posts raw-a))
                               (posts-assoc-b (assoc 'cl-bbs/models::posts raw-b))
                               (posts-a (get-flat-posts posts-assoc-a))
                               (posts-b (get-flat-posts posts-assoc-b))
                               (date-a (or (cdr (assoc 'cl-bbs/models::date (cdr (car (last posts-a))))) ""))
                               (date-b (or (cdr (assoc 'cl-bbs/models::date (cdr (car (last posts-b))))) "")))
                          (string> date-a date-b)))))
               (list-entries
                (mapcar (lambda (t-entry)
                          (let* ((id (car t-entry))
                                 (t-data (cdr t-entry))
                                 (raw-t (if (and (consp t-data) (consp (car t-data)) (consp (caar t-data))) (car t-data) t-data))
                                 (posts-assoc (assoc 'cl-bbs/models::posts raw-t))
                                 (posts (get-flat-posts posts-assoc))
                                 (headline (cdr (assoc 'cl-bbs/models::headline raw-t)))
                                 (date (cdr (assoc 'cl-bbs/models::date (cdr (car (last posts))))))
                                 (messages (length posts)))
                            `(,id (cl-bbs/models::headline . ,headline) (cl-bbs/models::date . ,date) (cl-bbs/models::messages . ,messages))))
                        sorted-threads))
               (frontpage-count (min 10 (length sorted-threads)))
               (index-entries
                (mapcar (lambda (t-entry)
                          (let* ((id (car t-entry))
                                 (t-data (cdr t-entry))
                                 (raw-t (if (and (consp t-data) (consp (car t-data)) (consp (caar t-data))) (car t-data) t-data))
                                 (headline (cdr (assoc 'cl-bbs/models::headline raw-t)))
                                 (posts-assoc (assoc 'cl-bbs/models::posts raw-t))
                                 (posts (get-flat-posts posts-assoc))
                                 (truncated (if (> (length posts) 6) t nil))
                                 (selected-posts (if (> (length posts) 6) (cons (car posts) (last posts 5)) posts)))
                            `(,id (cl-bbs/models::headline . ,headline) (cl-bbs/models::truncated . ,truncated) (cl-bbs/models::posts ,selected-posts))))
                        (subseq sorted-threads 0 frontpage-count)))
               (list-path (merge-pathnames "list" board-dir))
               (index-path (merge-pathnames "index" board-dir)))
          (write-sexp-file list-path list-entries)
          (write-sexp-file index-path index-entries))
        (let ((list-path (merge-pathnames "list" board-dir))
              (index-path (merge-pathnames "index" board-dir)))
          (when (probe-file list-path) (delete-file list-path))
          (when (probe-file index-path) (delete-file index-path))))))

(defun delete-thread-file (board thread-id)
  (let ((thread-path (merge-pathnames (format nil "sexp/~a/~a" board thread-id) *base-dir*)))
    (when (probe-file thread-path)
      (delete-file thread-path)
      (regenerate-board-index board))))

(defun delete-thread-comment (board thread-id comment-id)
  (let ((thread-path (merge-pathnames (format nil "sexp/~a/~a" board thread-id) *base-dir*)))
    (when (probe-file thread-path)
      (let* ((thread-data (read-sexp-file thread-path))
             (raw-thread (if (and (consp thread-data) (consp (car thread-data)) (consp (caar thread-data))) (car thread-data) thread-data))
             (posts-assoc (assoc 'cl-bbs/models::posts raw-thread)))
        (when posts-assoc
          (let* ((actual-posts (get-flat-posts posts-assoc))
                 (new-posts (remove-if (lambda (p) (= (car p) comment-id)) actual-posts)))
            (if (null new-posts)
                (delete-file thread-path)
                (progn
                  (setf (cdr posts-assoc) (list new-posts))
                  (write-sexp-file thread-path thread-data)))
            (regenerate-board-index board)))))))

(defun edit-thread-comment (board thread-id comment-id new-content &optional new-headline)
  (let ((thread-path (merge-pathnames (format nil "sexp/~a/~a" board thread-id) *base-dir*)))
    (when (probe-file thread-path)
      (let* ((thread-data (read-sexp-file thread-path))
             (raw-thread (if (and (consp thread-data) (consp (car thread-data)) (consp (caar thread-data))) (car thread-data) thread-data))
             (posts-assoc (assoc 'cl-bbs/models::posts raw-thread)))
        (when posts-assoc
          (let* ((actual-posts (get-flat-posts posts-assoc))
                 (new-posts (mapcar (lambda (p)
                                      (if (= (car p) comment-id)
                                          (cons (car p)
                                                (mapcar (lambda (kv)
                                                          (if (eq (car kv) 'cl-bbs/models::content)
                                                              (cons (car kv) new-content)
                                                              kv))
                                                        (cdr p)))
                                          p))
                                    actual-posts)))
            (setf (cdr posts-assoc) (list new-posts))
            (when (and (= comment-id 1) new-headline)
              (let ((headline-assoc (assoc 'cl-bbs/models::headline raw-thread)))
                (if headline-assoc
                    (setf (cdr headline-assoc) new-headline)
                    (setf raw-thread (append raw-thread (list (cons 'cl-bbs/models::headline new-headline)))))))
            (write-sexp-file thread-path thread-data)
            (regenerate-board-index board)))))))

(defun get-date ()
  (multiple-value-bind (second minute hour date month year)
      (get-decoded-time)
    (declare (ignore second))
    (format nil "~4,'0d-~2,'0d-~2,'0d ~2,'0d:~2,'0d"
            year month date hour minute)))

(defun get-next-thread-number (threads)
  (if (null threads)
      1
      (1+ (apply #'max (mapcar #'car threads)))))

(defun create-thread (path headline date message)
  (let ((thread `((cl-bbs/models::headline . ,headline)
                  (cl-bbs/models::posts . ((1 (cl-bbs/models::date . ,date) (cl-bbs/models::vip . nil) (cl-bbs/models::content . ,message)))))))
    (write-sexp-file path thread)))

(defun add-thread-to-list (path thread-number headline date)
  (let ((threads (read-sexp-file path)))
    (write-sexp-file path
                     (cons `(,thread-number (cl-bbs/models::headline . ,headline) (cl-bbs/models::date . ,date) (cl-bbs/models::messages . 1))
                           threads))))

(defun add-thread-to-index (path thread-number headline date message)
  (let* ((threads (read-sexp-file path))
         (thread `(,thread-number
                    (cl-bbs/models::headline . ,headline)
                    (cl-bbs/models::truncated . nil)
                    (cl-bbs/models::posts ((1 (cl-bbs/models::date . ,date) (cl-bbs/models::vip . nil) (cl-bbs/models::content . ,message)))))))
    (write-sexp-file path (cons thread threads))))

(defun update-thread-data (thread-data new-post)
  (let* ((raw-thread (if (and (consp thread-data)
                             (consp (car thread-data))
                             (consp (caar thread-data)))
                         (car thread-data)
                         thread-data))
         (posts-assoc (assoc 'cl-bbs/models::posts raw-thread)))
    (if posts-assoc
        (let* ((posts-list (if (listp (cdr posts-assoc)) (if (listp (cadr posts-assoc)) (cadr posts-assoc) (cdr posts-assoc)) (cdr posts-assoc)))
               (actual-posts (if (listp (car posts-list)) posts-list (list posts-list)))
               (updated-posts (append actual-posts (list new-post))))
          (setf (cdr posts-assoc) (list updated-posts))
          thread-data)
        (append thread-data (list `(cl-bbs/models::posts (,new-post)))))))

(defun handle-request (env)
  (let* ((path-info (getf env :path-info))
         (method (getf env :request-method))
         (parts (remove "" (cl-ppcre:split "/" path-info) :test #'string=))
         (query-string (getf env :query-string)))
    
    (cond
      ;; The static middleware intercepts /static/ beforehand.
      ;; We serve the index.html from static dir on root natively.
      ((string= path-info "/")
       (let ((index-file (pathname (or (uiop:getenv "SBBS_INDEX_FILE")
                                       (merge-pathnames "src/static/index.html" (asdf:system-source-directory :cl-bbs/server))))))
         (if (probe-file index-file)
             (let* ((html-content (uiop:read-file-string index-file))
                    (boards-list-html (generate-boards-html-list))
                    (dynamic-html (cl-ppcre:regex-replace-all "<!--BOARDS-LIST-PLACEHOLDER-->" html-content (lambda (match &rest regs) (declare (ignore match regs)) boards-list-html))))
               `(200 (:content-type "text/html; charset=utf-8")
                     (,dynamic-html)))
             `(200 (:content-type "text/plain") ("SchemeBBS clone root")))))

      ((string= path-info "/about")
       (let ((about-file (pathname (merge-pathnames "src/static/about.html" (asdf:system-source-directory :cl-bbs/server)))))
         (if (probe-file about-file)
             `(200 (:content-type "text/html; charset=utf-8")
                   (,(uiop:read-file-string about-file)))
             `(404 (:content-type "text/plain") ("About page not found")))))

      ;; 1. GET /admin (Admin Control Panel)
      ((string= path-info "/admin")
       (if (not (authenticate-admin env))
           `(401 (:content-type "text/plain" "WWW-Authenticate" "Basic realm=\"cl-bbs Admin\"") ("Unauthorized"))
           (let* ((sexp-dir (merge-pathnames "sexp/" *base-dir*))
                  (paths (and (probe-file sexp-dir) (uiop:subdirectories sexp-dir)))
                  (boards (sort (mapcar (lambda (path) (car (last (pathname-directory path)))) paths) #'string<))
                  (params (and (getf env :query-string) (quri:url-decode-params (getf env :query-string))))
                  (board (cdr (assoc "board" params :test #'string=)))
                  (thread-id-str (cdr (assoc "thread" params :test #'string=)))
                  (theme (get-theme-from-env env))
                  (threads nil)
                  (comments nil)
                  (headline nil))
             ;; If board is selected, load its threads from list or directory
             (when (and board (member board boards :test #'string=))
               (let ((list-path (merge-pathnames (format nil "sexp/~a/list" board) *base-dir*)))
                 (when (probe-file list-path)
                   (setf threads (read-sexp-file list-path)))))
             ;; If thread is selected, load its comments
             (when (and board thread-id-str)
               (let ((thread-path (merge-pathnames (format nil "sexp/~a/~a" board thread-id-str) *base-dir*)))
                 (when (probe-file thread-path)
                   (let* ((thread-data (read-sexp-file thread-path))
                          (raw-thread (if (and (consp thread-data) (consp (car thread-data)) (consp (caar thread-data))) (car thread-data) thread-data))
                          (posts-assoc (assoc 'cl-bbs/models::posts raw-thread)))
                     (setf headline (cdr (assoc 'cl-bbs/models::headline raw-thread)))
                     (when posts-assoc
                       (setf comments (get-flat-posts posts-assoc)))))))
             `(200 (:content-type "text/html; charset=utf-8")
                   (,(render-moderation boards board threads thread-id-str comments theme headline))))))

      ;; 2. POST /admin/action (Admin Actions)
      ((string= path-info "/admin/action")
       (if (not (authenticate-admin env))
           `(401 (:content-type "text/plain" "WWW-Authenticate" "Basic realm=\"cl-bbs Admin\"") ("Unauthorized"))
           (let* ((body-bytes (make-array (getf env :content-length) :element-type '(unsigned-byte 8)))
                  (_ (read-sequence body-bytes (getf env :raw-body)))
                  (body-str (flexi-streams:octets-to-string body-bytes :external-format :utf-8))
                  (params (quri:url-decode-params body-str))
                  (action (cdr (assoc "action" params :test #'string=)))
                  (board (cdr (assoc "board" params :test #'string=)))
                  (thread-id-str (cdr (assoc "thread" params :test #'string=)))
                  (comment-id-str (cdr (assoc "comment" params :test #'string=)))
                  (content (cdr (assoc "content" params :test #'string=))))
             (cond
               ((string= action "delete-board")
                (delete-board-dir board)
                `(303 (:location "/admin") ("Redirecting...")))
               ((string= action "delete-thread")
                (delete-thread-file board thread-id-str)
                `(303 (:location ,(format nil "/admin?board=~a" board)) ("Redirecting...")))
               ((string= action "delete-comment")
                (let ((cid (and comment-id-str (parse-integer comment-id-str :junk-allowed t))))
                  (when cid
                    (delete-thread-comment board thread-id-str cid)))
                `(303 (:location ,(format nil "/admin?board=~a&thread=~a" board thread-id-str)) ("Redirecting...")))
               ((string= action "edit-comment")
                (let ((cid (and comment-id-str (parse-integer comment-id-str :junk-allowed t)))
                      (headline (cdr (assoc "headline" params :test #'string=))))
                  (when cid
                    (edit-thread-comment board thread-id-str cid content headline)))
                `(303 (:location ,(format nil "/admin?board=~a&thread=~a" board thread-id-str)) ("Redirecting...")))
               (t
                `(400 (:content-type "text/plain") ("Invalid Action")))))))

      ((string= path-info "/sw.js")
       (let ((sw-file (merge-pathnames "src/static/sw.js" (asdf:system-source-directory :cl-bbs/server))))
         (if (probe-file sw-file)
             `(200 (:content-type "application/javascript")
                   (,(uiop:read-file-string sw-file)))
             `(404 (:content-type "text/plain") ("Service worker not found")))))

      ((string= path-info "/manifest.json")
       (let ((manifest-file (merge-pathnames "src/static/manifest.json" (asdf:system-source-directory :cl-bbs/server))))
         (if (probe-file manifest-file)
             `(200 (:content-type "application/json")
                   (,(uiop:read-file-string manifest-file)))
             `(404 (:content-type "text/plain") ("Manifest not found")))))
      
      ((and (eq method :get)
            (= (length parts) 1))
       (let* ((board (first parts))
              (theme (get-theme-from-env env))
              (index-path (merge-pathnames (format nil "sexp/~a/index" board) *base-dir*)))
          (if (probe-file index-path)
             (let ((index-data (read-sexp-file index-path)))
                `(200 (:content-type "text/html; charset=utf-8")
                      (,(render-index board index-data theme))))
             `(200 (:content-type "text/html; charset=utf-8")
                   (,(render-index board nil theme))))))

      ((and (eq method :get)
            (= (length parts) 2)
            (string= (second parts) "list"))
       (let* ((board (first parts))
              (theme (get-theme-from-env env))
              (list-path (merge-pathnames (format nil "sexp/~a/list" board) *base-dir*)))
          (if (probe-file list-path)
             (let ((list-data (read-sexp-file list-path)))
                `(200 (:content-type "text/html; charset=utf-8")
                      (,(render-list board list-data theme))))
             `(200 (:content-type "text/html; charset=utf-8")
                   (,(render-list board nil theme))))))

      ((and (eq method :get)
            (= (length parts) 2)
            (string= (second parts) "preferences"))
       (let* ((board (first parts))
              (theme (get-theme-from-env env)))
         `(200 (:content-type "text/html; charset=utf-8")
               (,(render-preferences board theme)))))

      ((and (eq method :get)
            (= (length parts) 2))
       (let* ((board (first parts))
              (thread-id (second parts))
              (theme (get-theme-from-env env))
              (thread-path (merge-pathnames (format nil "sexp/~a/~a" board thread-id) *base-dir*)))
         (if (probe-file thread-path)
             (let ((thread-data (read-sexp-file thread-path)))
                `(200 (:content-type "text/html; charset=utf-8")
                      (,(render-thread board thread-id thread-data nil theme))))
             `(404 (:content-type "text/plain") ("Thread not found")))))

      ((and (eq method :get)
            (= (length parts) 3))
       (let* ((board (first parts))
              (thread-id (second parts))
              (range-str (third parts))
              (theme (get-theme-from-env env))
              (thread-path (merge-pathnames (format nil "sexp/~a/~a" board thread-id) *base-dir*)))
         (if (probe-file thread-path)
             (let ((thread-data (read-sexp-file thread-path)))
                `(200 (:content-type "text/html; charset=utf-8")
                      (,(render-thread board thread-id thread-data range-str theme))))
             `(404 (:content-type "text/plain") ("Thread not found")))))

      ;; POST handlers
      ((and (eq method :post)
            (= (length parts) 2)
            (string= (second parts) "preferences"))
       (let* ((board (first parts))
              (body-bytes (make-array (getf env :content-length) :element-type '(unsigned-byte 8)))
              (_ (read-sequence body-bytes (getf env :raw-body)))
              (body-str (flexi-streams:octets-to-string body-bytes :external-format :utf-8))
              (params (quri:url-decode-params body-str))
              (theme (cdr (assoc "theme" params :test #'string=))))
         `(303 (:location ,(format nil "/~a/preferences" board)
               "Set-Cookie" ,(format nil "theme=~a; Path=/; Max-Age=31536000" (or theme "default")))
               ("Redirecting..."))))

      ((and (eq method :post)
            (= (length parts) 2)
            (string= (second parts) "post"))
       ;; New thread
       (let* ((board (first parts))
              (body-bytes (make-array (getf env :content-length) :element-type '(unsigned-byte 8)))
              (_ (read-sequence body-bytes (getf env :raw-body)))
              (body-str (flexi-streams:octets-to-string body-bytes :external-format :utf-8))
              (params (quri:url-decode-params body-str))
              (epistula (cdr (assoc "epistula" params :test #'string=)))
              (titulus (cdr (assoc "titulus" params :test #'string=)))
              (date (get-date))
              (list-path (merge-pathnames (format nil "sexp/~a/list" board) *base-dir*))
              (index-path (merge-pathnames (format nil "sexp/~a/index" board) *base-dir*))
              (threads (read-sexp-file list-path))
              (thread-number (get-next-thread-number threads))
              (thread-path (merge-pathnames (format nil "sexp/~a/~a" board thread-number) *base-dir*)))
         
         (if (or (null epistula)
                 (string= "" (string-trim '(#\Space #\Tab #\Newline #\Return) epistula)))
             (let ((theme (get-theme-from-env env)))
               `(400 (:content-type "text/html; charset=utf-8")
                     (,(render-error-page "Post body cannot be empty" theme))))
             (progn
               (ensure-board-dirs board)
               (create-thread thread-path titulus date epistula)
               (add-thread-to-list list-path thread-number titulus date)
               (add-thread-to-index index-path thread-number titulus date epistula)
               `(303 (:location ,(format nil "/~a/" board)) ("Redirecting..."))))))

      ((and (eq method :post)
            (= (length parts) 3)
            (string= (third parts) "post"))
       ;; Reply to thread
       (let* ((board (first parts))
              (thread-id (second parts))
              (body-bytes (make-array (getf env :content-length) :element-type '(unsigned-byte 8)))
              (_ (read-sequence body-bytes (getf env :raw-body)))
              (body-str (flexi-streams:octets-to-string body-bytes :external-format :utf-8))
              (params (quri:url-decode-params body-str))
              (epistula (cdr (assoc "epistula" params :test #'string=)))
              (date (get-date))
              (thread-path (merge-pathnames (format nil "sexp/~a/~a" board thread-id) *base-dir*)))
         (if (or (null epistula)
                 (string= "" (string-trim '(#\Space #\Tab #\Newline #\Return) epistula)))
             (let ((theme (get-theme-from-env env)))
               `(400 (:content-type "text/html; charset=utf-8")
                     (,(render-error-page "Post body cannot be empty" theme))))
             (if (probe-file thread-path)
                 (let* ((thread-data (read-sexp-file thread-path))
                        (raw-thread (if (and (consp thread-data)
                                             (consp (car thread-data))
                                             (consp (caar thread-data)))
                                        (car thread-data)
                                        thread-data))
                        (posts-assoc (let ((assoc-result (assoc 'cl-bbs/models::posts raw-thread))) (if assoc-result assoc-result (cadr (if (consp thread-data) thread-data (list thread-data))))))
                        (posts-list (if (listp (cdr posts-assoc)) (if (listp (cadr posts-assoc)) (cadr posts-assoc) (cdr posts-assoc)) (cdr posts-assoc)))
                        (posts (if (listp (car posts-list)) posts-list (list posts-list)))
                        (new-post `(,(1+ (reduce #'max posts :key #'car :initial-value 0)) (cl-bbs/models::date . ,date) (cl-bbs/models::vip . nil) (cl-bbs/models::content . ,epistula)))
                        (new-thread-data (update-thread-data thread-data new-post)))
                   (write-sexp-file thread-path new-thread-data)
                   
                   ;; Update list metadata
                   (let* ((list-path (merge-pathnames (format nil "sexp/~a/list" board) *base-dir*))
                          (threads-list (read-sexp-file list-path))
                          (str-id (if (stringp thread-id) (parse-integer thread-id) thread-id))
                          (target-thread-assoc (assoc str-id threads-list)))
                     (when target-thread-assoc
                       (let* ((rem-threads (remove str-id threads-list :key #'car :test #'equal))
                              (raw-new-thread (if (and (consp new-thread-data)
                                                       (consp (car new-thread-data))
                                                       (consp (caar new-thread-data)))
                                                  (car new-thread-data)
                                                  new-thread-data))
                              (messages-count (length (cadr (assoc 'cl-bbs/models::posts raw-new-thread))))
                              (updated-entry `(,str-id 
                                                (cl-bbs/models::headline . ,(if (stringp (cdr (assoc 'cl-bbs/models::headline (cdr target-thread-assoc)))) (cdr (assoc 'cl-bbs/models::headline (cdr target-thread-assoc))) (cdr (assoc 'headline (cdr target-thread-assoc)))))
                                                (cl-bbs/models::date . ,date) 
                                                (cl-bbs/models::messages . ,messages-count))))
                         (write-sexp-file list-path (cons updated-entry rem-threads))))
                     
                     ;; Update index metadata
                     (let* ((index-path (merge-pathnames (format nil "sexp/~a/index" board) *base-dir*))
                            (index-list (read-sexp-file index-path))
                            (target-index-assoc (assoc str-id index-list)))
                       (when target-index-assoc
                         (let* ((rem-index (remove str-id index-list :key #'car :test #'equal))
                                (raw-new-thread (if (and (consp new-thread-data)
                                                         (consp (car new-thread-data))
                                                         (consp (caar new-thread-data)))
                                                    (car new-thread-data)
                                                    new-thread-data))
                                (updated-entry `(,str-id 
                                                  (cl-bbs/models::headline . ,(if (stringp (cdr (assoc 'cl-bbs/models::headline (cdr target-index-assoc)))) (cdr (assoc 'cl-bbs/models::headline (cdr target-index-assoc))) (cdr (assoc 'headline (cdr target-index-assoc)))))
                                                  (cl-bbs/models::truncated . nil)
                                                  (cl-bbs/models::posts ,(cadr (assoc 'cl-bbs/models::posts raw-new-thread))))))
                           (write-sexp-file index-path (cons updated-entry rem-index))))))
                   `(303 (:location ,(format nil "/~a/" board)) ("Redirecting...")))
                 `(404 (:content-type "text/plain") ("Thread not found"))))))

      (t
       `(404 (:content-type "text/plain") ("Not found"))))))